name: Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - 'ci/**'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Initialize pacman keyring
        run: |
          pacman-key --init
          pacman-key --populate archlinux

      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm \
            base-devel \
            git \
            hyprland \
            pango \
            cairo \
            libdrm \
            libinput \
            pixman \
            wayland \
            libxkbcommon \
            pkgconf

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build plugin
        run: make all

      - name: Create release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: hyprexpo.so
          generate_release_notes: true
